version: '3.8'
services:
  bouncer-mikrotik-dev:
    container_name: bouncer-mikrotik-dev
    image: quay.io/kaszpir/cs-mikrotik-bouncer-alt:latest
    env_file: ".env"
    ports:
      - 2112:2112/tcp # default metrics port
      - 40000:40000/tcp # https://ko.build/features/debugging/
    read_only: true
    restart: unless-stopped
    privileged: false
    cap_drop:
      - ALL
